# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tunnel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tunnel.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctunnel.proto\"\x83\x02\n\x06Tunnel\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\x17\n\x0fsequence_number\x18\x02 \x01(\r\x12\x1e\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x0e.Tunnel.Action\x12$\n\tdirection\x18\x04 \x01(\x0e\x32\x11.Tunnel.Direction\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\r\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\"/\n\x06\x41\x63tion\x12\t\n\x05start\x10\x00\x12\x07\n\x03\x65nd\x10\x01\x12\x08\n\x04\x64\x61ta\x10\x02\x12\x07\n\x03\x61\x63k\x10\x03\"+\n\tDirection\x12\x0c\n\x08to_proxy\x10\x00\x12\x10\n\x0cto_forwarder\x10\x01')
)



_TUNNEL_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='Tunnel.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='start', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='end', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='data', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ack', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=184,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_TUNNEL_ACTION)

_TUNNEL_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='Tunnel.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='to_proxy', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='to_forwarder', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=233,
  serialized_end=276,
)
_sym_db.RegisterEnumDescriptor(_TUNNEL_DIRECTION)


_TUNNEL = _descriptor.Descriptor(
  name='Tunnel',
  full_name='Tunnel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='Tunnel.client_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='Tunnel.sequence_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Tunnel.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Tunnel.direction', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Tunnel.ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Tunnel.port', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Tunnel.payload', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TUNNEL_ACTION,
    _TUNNEL_DIRECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=276,
)

_TUNNEL.fields_by_name['action'].enum_type = _TUNNEL_ACTION
_TUNNEL.fields_by_name['direction'].enum_type = _TUNNEL_DIRECTION
_TUNNEL_ACTION.containing_type = _TUNNEL
_TUNNEL_DIRECTION.containing_type = _TUNNEL
DESCRIPTOR.message_types_by_name['Tunnel'] = _TUNNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tunnel = _reflection.GeneratedProtocolMessageType('Tunnel', (_message.Message,), dict(
  DESCRIPTOR = _TUNNEL,
  __module__ = 'tunnel_pb2'
  # @@protoc_insertion_point(class_scope:Tunnel)
  ))
_sym_db.RegisterMessage(Tunnel)


# @@protoc_insertion_point(module_scope)
